name = "AlDente"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/AlDente",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.apphousekitchen.aldente-pro.plist",
]
[block.when]
os = "macos"
