name = "Bartender"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Bartender/Bartender.BartenderPreferences",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{com.surteesstudios.Bartender-setapp.plist,com.surteesstudios.Bartender.plist}",
]
[block.when]
os = "macos"
