name = "BetterSnapTool"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/BetterSnapTool",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.hegenberg.BetterSnapTool.plist",
]
[block.when]
os = "macos"
