name = "BetterTouchTool"
files = [
    "${MACKUP_XDG_CONFIG}/BetterTouchTool/{bettersnaptool.bttlicense,bettertouchtool.license,btt_data_store.v2,btt_data_store.v2-shm,btt_data_store.v2-wal,bttdata2}",
    "Library/Preferences/com.hegenberg.BetterTouchTool.plist",
]
