name = "Beyond Compare"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Beyond Compare/{BC4Key.txt,BCColors.xml,BCCommands.xml,BCPreferences.xml}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.ScooterSoftware.BeyondCompare.plist",
]
[block.when]
os = "macos"
