name = "Boxer"

[[block]]
files = [
    "Applications/DOS Games",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/net.washboardabs.boxer.plist",
]
[block.when]
os = "macos"
