name = "Brackets"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Brackets",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/io.brackets.appshell.plist",
]
[block.when]
os = "macos"
