name = "ClipMenu"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/ClipMenu",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.naotaka.ClipMenu.plist",
]
[block.when]
os = "macos"
