name = "Coda 2"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Coda 2",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.panic.Coda2.plist",
]
[block.when]
os = "macos"
