name = "Colloquy"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Colloquy",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/info.colloquy.plist",
]
[block.when]
os = "macos"
