name = "DaisyDisk"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/DaisyDisk/License.DaisyDisk",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.daisydiskapp.DaisyDiskStandAlone.plist",
]
[block.when]
os = "macos"
