name = "Dolphin"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Dolphin",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/org.dolphin-emu.dolphin.plist",
]
[block.when]
os = "macos"
