name = "GrandTotal 3"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/GrandTotal/AddressBook.plist",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.mediaatelier.GrandTotal3.plist",
]
[block.when]
os = "macos"
