name = "HyperDock"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/HyperDock",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{de.bahoom.HyperDock.plist,de.bahoom.HyperDock.prefpane.plist}",
]
[block.when]
os = "macos"
