name = "IntelliJ IDEA (macOS)"
files = [
    "Library/Preferences/{IdeaIC2016.1,IdeaIC2016.2,IdeaIC2016.3,IdeaIC2017.1,IdeaIC2017.2,IdeaIC2017.3,IdeaIC2018.2,IdeaIC2018.3,IdeaIC2019.1,IntelliJIdea12,IntelliJIdea13,IntelliJIdea14,IntelliJIdea15,IntelliJIdea2016.1,IntelliJIdea2016.2,IntelliJIdea2016.3,IntelliJIdea2017.1,IntelliJIdea2017.2,IntelliJIdea2017.3,IntelliJIdea2018.1,IntelliJIdea2018.2,IntelliJIdea2018.3,IntelliJIdea2019.1,IntelliJIdea2019.2,IntelliJIdea2019.3}",
]

[when]
os = "macos"
