name = "Jumpcut"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Jumpcut",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/net.sf.Jumpcut.plist",
]
[block.when]
os = "macos"
