name = "Karabiner"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Karabiner",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{org.pqrs.Karabiner-AXNotifier.plist,org.pqrs.Karabiner.multitouchextension.plist,org.pqrs.Karabiner.plist}",
]
[block.when]
os = "macos"
