name = "KeePassXC"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/keepassxc/keepassxc.ini",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/org.keepassxc.keepassxc.plist",
]
[block.when]
os = "macos"
