name = "KeyRemap4MacBook"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/KeyRemap4MacBook/private.xml",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{org.pqrs.KeyRemap4MacBook.multitouchextension.plist,org.pqrs.KeyRemap4MacBook.plist}",
]
[block.when]
os = "macos"
