name = "Light Table"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/LightTable/{plugins,settings,User}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.kodowa.LightTable.plist",
]
[block.when]
os = "macos"
