name = "LittleSnitch"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Little Snitch/{configuration.user.xpl,configuration.xpl,configuration4.user.xpl,rules.usr.xpl}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{at.obdev.littlesnitch.networkmonitor.plist,at.obdev.LittleSnitchNetworkMonitor.plist}",
]
[block.when]
os = "macos"
