name = "Loopback"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Loopback/Devices.plist",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.rogueamoeba.Loopback.plist",
]
[block.when]
os = "macos"
