name = "MacDown"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/MacDown/{Styles,Themes}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.uranusjr.macdown.plist",
]
[block.when]
os = "macos"
