name = "Mailmate"
files = [
    "${MACKUP_XDG_CONFIG}/Mailmate/{com.freron.MailMate.pid,Identities.plist,Mailboxes.plist,Signatures.plist,Sources.plist,Submission.plist,Tags.plist}",
    "${MACKUP_XDG_CONFIG}/Mailmate/Resources/KeyBindings",
]
