name = "MySQL Workbench"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/MySQL/Workbench/{connections.xml,server_instances.xml,wb_options.xml}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.oracle.mysql.workbench.plist",
]
[block.when]
os = "macos"
