name = "Name Mangler"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Name Mangler",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.manytricks.NameMangler.plist",
]
[block.when]
os = "macos"
