name = "nvALT"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Notational Velocity",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/net.elasticthreads.nv.plist",
]
[block.when]
os = "macos"
