name = "OmniFocus"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/OmniFocus/{Plug-Ins,Themes}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.omnigroup.OmniFocus.plist",
]
[block.when]
os = "macos"
