name = "Path Finder"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Path Finder",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.cocoatech.PathFinder.plist",
]
[block.when]
os = "macos"
