name = "Adobe Photoshop"
files = [
    "${MACKUP_XDG_CONFIG}/Adobe/Adobe Photoshop CC 2013/Presets",
    "${MACKUP_XDG_CONFIG}/Adobe/Adobe Photoshop CC 2014/Presets",
    "${MACKUP_XDG_CONFIG}/Adobe/Adobe Photoshop CC 2015/Presets",
    "${MACKUP_XDG_CONFIG}/Adobe/Adobe Photoshop CC 2015.5/Presets",
    "${MACKUP_XDG_CONFIG}/Adobe/Adobe Photoshop CC 2019/Presets",
]
