name = "poetry"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/pypoetry/config.toml",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/pypoetry/config.toml",
]
[block.when]
os = "macos"
