name = "PokerStars (macOS)"
files = [
    "Library/Preferences/{com.pokerstars.eu.user.ini,com.pokerstars.PokerStars.plist,com.pokerstars.PokerStarsEU.plist,com.pokerstars.user.ini}",
]

[when]
os = "macos"
