name = "PokerStars"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/{PokerStars,PokerStarsEU}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{com.pokerstars.eu.user.ini,com.pokerstars.PokerStars.plist,com.pokerstars.PokerStarsEU.plist,com.pokerstars.user.ini}",
]
[block.when]
os = "macos"
