name = "Quicksilver"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Quicksilver",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.blacktree.Quicksilver.plist",
]
[block.when]
os = "macos"
