name = "R"

[[block]]
files = [
    ".R",
    ".Rhistory",
    ".Rprofile",
    ".Rprofile.d",
    ".Renviron",
    ".Renviron.d",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/org.R-project.R.plist",
]
[block.when]
os = "macos"
