name = "Rocket"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Rocket",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/net.matthewpalmer.Rocket.plist",
]
[block.when]
os = "macos"
