name = "Royal TSX"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Royal TSX/{License.xml,UserPreferences.config}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.lemonmojo.RoyalTSX.App.plist",
]
[block.when]
os = "macos"
