name = "RustRover"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/JetBrains/{RustRover2025.2,RustRover2025.3}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{RustRover2025.2,RustRover2025.3}",
]
[block.when]
os = "macos"
