name = "SecureCRT"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/VanDyke/SecureCRT/Config",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.vandyke.SecureCRT.plist",
]
[block.when]
os = "macos"
