name = "Spectacle"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Spectacle",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.divisiblebyzero.Spectacle.plist",
]
[block.when]
os = "macos"
