name = "Stay"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Stay",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/com.cordlessdog.Stay.plist",
]
[block.when]
os = "macos"
