name = "Swinsian"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Swinsian/{Library.sqlite,License.swinsianlicense}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{com.swinsian.Swinsian.plist,com.swinsian.SwinsianDesktopWindow.plist}",
]
[block.when]
os = "macos"
