name = "Ubersicht"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/Übersicht/widgets",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/tracesOf.Uebersicht.plist",
]
[block.when]
os = "macos"
