name = "VLC"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/[mac:org.videolan.vlc,vlc]",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{org.videolan.vlc,org.videolan.vlc.LSSharedFileList.plist,org.videolan.vlc.plist}",
]
[block.when]
os = "macos"
