name = "WhatsApp Web"

[[block]]
files = [
    "${MACKUP_XDG_CONFIG}/WhatsApp/{Preferences,settings.json}",
]
[block.when]
not_os = "macos"

[[block]]
files = [
    "Library/Preferences/{WhatsApp-Helper.plist,WhatsApp.plist}",
]
[block.when]
os = "macos"
